###
GET http://localhost:8000

#### User API #####
###
GET http://localhost:8000/user/63bf6bfbbc4a4daa0707d936
###
POST http://localhost:8000/user
Content-Type: application/json

{
    "firstname":"Bhim",
    "lastname":"Adhikari",
    "username":"ad_bhim",
    "password": "123456a"

}

###
POST http://localhost:8000/user/login
Content-Type: application/json

{
    "username":"ad_sulav",
    "password": "123456a"
}

###
PUT http://localhost:8000/user/update
Content-Type: application/json

{
    "username":"ad_sulav",
    "password":"123456a",
    "lastname":"DON"
}

###
DELETE http://localhost:8000/user/63c0acbb158cd24d41da0b0b

###
PUT http://localhost:8000/user/63c64425f5c308435b3fe400/follow
Content-Type: application/json

{
    "currentId":"63c64432f5c308435b3fe402"
}